source("R/config.R")
source("R/chromMap.R")
source("R/dataTable.R")
source("R/geneView.R")
source("R/progeneView.R")
source("R/proPrediction.R")
source("R/selectionPanel.R")
source("R/sequencingPDF.R")
source("R/snpCount.R")
source("R/tutorial.R")
source("R/variants.R")
source("R/app.R")

yEvoMutBrowser()
