name: Generate README PDF

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: "ls -a"
      - uses: docker://pandoc/extra:latest
        with:
          args: >-
            --pdf-engine=lualatex
            --output=README.pdf
            -f markdown-implicit_figures
            -V geometry:margin=1in
            -V mainfont:SourceSansPro
            -V monofont:SourceCodePro
            README.md
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add README.pdf
          git commit -m "Add README PDF"
          git fetch origin main
          git push origin main
